"""add otp_verify_attempts table

Revision ID: 1e03799b6487
Revises: 3d8c33203270
Create Date: 2026-07-01 00:51:14.028889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e03799b6487'
down_revision: Union[str, Sequence[str], None] = '3d8c33203270'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_verify_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=False),
    sa.Column('attempted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_verify_attempts_attempted_at'), 'otp_verify_attempts', ['attempted_at'], unique=False)
    op.create_index(op.f('ix_otp_verify_attempts_phone_number'), 'otp_verify_attempts', ['phone_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_otp_verify_attempts_phone_number'), table_name='otp_verify_attempts')
    op.drop_index(op.f('ix_otp_verify_attempts_attempted_at'), table_name='otp_verify_attempts')
    op.drop_table('otp_verify_attempts')
    # ### end Alembic commands ###
