"""add media table and messages.media_id

Revision ID: 3d8c33203270
Revises: 74857a4a40ef
Create Date: 2026-07-01 00:19:04.968306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d8c33203270'
down_revision: Union[str, Sequence[str], None] = '74857a4a40ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Alembic autogenerate doesn't diff Postgres enum value sets -- added
    # by hand. Safe to run inside this migration's transaction on PG12+,
    # as long as the new values aren't *used* until a later transaction.
    op.execute("ALTER TYPE message_type ADD VALUE IF NOT EXISTS 'image'")
    op.execute("ALTER TYPE message_type ADD VALUE IF NOT EXISTS 'file'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('uploader_id', sa.UUID(), nullable=False),
    sa.Column('storage_backend', sa.String(), nullable=False),
    sa.Column('storage_key', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('messages', sa.Column('media_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'messages', 'media', ['media_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'media_id')
    op.drop_table('media')
    # ### end Alembic commands ###
    # Note: Postgres has no ALTER TYPE ... DROP VALUE, so the 'image'/'file'
    # enum values added in upgrade() are intentionally left in place.
