"""add call fields to messages

Revision ID: c45921dba5a5
Revises: 1e03799b6487
Create Date: 2026-07-01 20:24:12.737121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c45921dba5a5'
down_revision: Union[str, Sequence[str], None] = '1e03799b6487'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Alembic autogenerate doesn't diff Postgres enum value sets -- added
    # by hand, same pattern as the earlier image/file addition to this
    # same enum. call_outcome below is a brand-new type, so that one
    # doesn't need this treatment -- only adding a value to an *existing*
    # type does.
    op.execute("ALTER TYPE message_type ADD VALUE IF NOT EXISTS 'call'")

    # A plain inline sa.Enum(...) on add_column does NOT auto-create the
    # Postgres type here -- must create it explicitly first.
    call_outcome_enum = sa.Enum('missed', 'completed', name='call_outcome')
    call_outcome_enum.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('call_outcome', call_outcome_enum, nullable=True))
    op.add_column('messages', sa.Column('call_video', sa.Boolean(), nullable=True))
    op.add_column('messages', sa.Column('call_duration_seconds', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'call_duration_seconds')
    op.drop_column('messages', 'call_video')
    op.drop_column('messages', 'call_outcome')
    # ### end Alembic commands ###
    sa.Enum(name='call_outcome').drop(op.get_bind())
    # Note: Postgres has no ALTER TYPE ... DROP VALUE, so the 'call'
    # message_type enum value added in upgrade() is intentionally left in place.
